[package]
name = "clsol"
version = "0.4.0"
authors = ["Erik Larson <erik@welarson.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1"
rssol = { git = "https://github.com/erikssource/rssol" }
